'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Game

    Partial Public Class _Default

        '''<summary>
        '''lblCharacters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCharacters As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCharacters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCharacters As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''sdsCharacters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sdsCharacters As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''lName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lName As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lHp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lHp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lExp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lExp As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lGold control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lGold As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''btnSelectCharacter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSelectCharacter As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''imgIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgIcon As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
