'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Map

    '''<summary>
    '''lName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lHp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lHp As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lXp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lXp As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lGold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lGold As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''imgIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lInventoryCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lInventoryCount As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInventory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnDrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDrop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''sdsInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsInventory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tbGameMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbGameMap As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''btnUpLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpLeft As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUpRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpRight As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLeft As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRight As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDownLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownLeft As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDown As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDownRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownRight As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dItemsFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dItemsFound As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lCantPickUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCantPickUp As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlMapItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMapItems As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnPickUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPickUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''sdsMapItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMapItems As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''tbWorldMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorldMap As Global.System.Web.UI.WebControls.Table
End Class
